<?php
print'
<!DOCTYPE html>
<html>
<html  lang="bg-BG">
<head>
	<meta charset="utf-8">
	<meta http-equiv="Content-Type" content="text/html; charset=windows-1251"/>
	<link rel="stylesheet" type="text/css" href="Style.css">
	<title>'.$page_title.'</title>
<script src="https://kit.fontawesome.com/acc09d4eff.js" crossorigin="anonymous"></script>

	
</head>
<body>
<header>
		<div class="lenta">
			<img src="images/logo.png" alt="logo">

		</div>

			<nav>
				
				<ul>
					<li class="active" > <a href="#">Начало</a></li>
					<li> <a href="#">Стекове</a></li>
					<li> <a href="#">Бургери</a></li>
					<li> <a href="#">Салати</a></li>
					<li> <a href="#">Напитки</a></li>
					<li> <a href="#">Предястия</a></li>
					<li> <a href="#">Десерти</a></li>
				</ul>
			</nav>
			
			
'
?>